# Generated by Django 3.0.2 on 2020-01-29 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200129_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stbuser',
            name='username',
        ),
    ]
